baseURL = "https://www.remoteunbound.com"
title = "RemoteUnbound"
copyright = "Copyright © 2023"
paginate = 7 
languageCode = "en"
DefaultContentLanguage = "en"
theme = "calligraphy"
enableInlineShortcodes = true
enableEmoji = true

[params]
  cdn = false
  description = "Welcome to Remote Unbound Magazine. Discover remote work tips, digital nomad lifestyle insights, and profitable remote business ideas to achieve freedom and success in the digital age."


[params.meta]
  baseOGImage = "img/screenshot.jpg"
  faviconComplete = true
  faviconSVG = true
  faviconVersion = ""
  faviconMSColor = "#00aba9"
  faviconiOSColor = "#00aba9"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
  identifier = "authors"
  name = "Authors"
  url = "/authors/"
  weight = 15

[[menu.main]]
  identifier = "series"
  name = "Series"
  url = "/series/"
  weight = 15

[[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 25


[[menu.main]]
  identifier = "tools"
  name = "Tools ▼ "
  url = "/tools/"
  weight = 28

  [[menu.main]]
    parent = "tools"
    name = "Savings Calculator"
    url = "/tools/savings-calculator/"
    weight = 1

  [[menu.main]]
    parent = "tools"
    name = "Salary Calculator"
    url = "/tools/salary-calculator/"
    weight = 2

  [[menu.main]]
    parent = "tools"
    name = "Deduction Calculator"
    url = "/tools/home-office-deduction-calculators/"
    weight = 2

[[menu.main]]
  identifier = "quiz"
  name = "Quiz"
  url = "/tools/what-business-should-i-start/"
  weight = 29

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 30

################################################################################
######       The block below has additional configuration settings.        #####
######         Users can edit, but for most it won't be necessary.         #####
################################################################################

[taxonomies]
  author = "authors"
  series = "series"
  category = "categories"
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.parser.attribute]
  block = true

[module.hugoVersion]
  extended = true
  min = "0.111.3"

[privacy.twitter]
  enableDNT = true

[privacy.vimeo]
  enableDNT = true

[privacy.youtube]
  privacyEnhanced = true
